File decryption over streams
TelegramBots/Telegram.Bot.Extensions.Passport pull request #1
Opened 2018-09-01 15:14 UTC by MihaZupan

2018-09-01 20:58 UTC, poulad requested changes
Master branch is merged. 2 test cases in driver license integration tests fail. Other than that, all is good.

If possible, use the same variable names as in the byte array method and provide consts with readable names instead of values like `81920`.

2018-09-02 10:55 UTC, MihaZupan commented on src/Telegram.Bot.Extensions.Passport/Decryption/Decrypter.cs
> -                if (!(32 <= paddingLength && paddingLength < 256))
Padding length will always be less than 256 since we're casting from a byte.

2018-09-02 10:57 UTC, MihaZupan commented on src/Telegram.Bot.Extensions.Passport/Decryption/Decrypter.cs
> -            if (encryptedContent.Length % 16 != 0)
This would throw an exception when dealing with web responses.

2018-09-02 12:41 UTC, poulad approved these changes

2018-09-02 16:23 UTC, merged

2025-10-27 13:25 UTC, smallkiller1 reviewed
Perfect